# Generated by Django 3.0.8 on 2020-07-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200719_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Institute',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
